export const Pages={
    access:{
        displayName:"アクセス",
        path:"/24th.kokasai.com/access",
        icon:`${process.env.PUBLIC_URL}/img/menuBarIcon/accessIcon.png`,
    },
    event:{
        displayName:"ステージ企画",
        path:"/24th.kokasai.com/event",
        icon:`${process.env.PUBLIC_URL}/img/menuBarIcon/eventIcon.png`,
    },
    home:{
        displayName:"ホーム",
        path:"/24th.kokasai.com",
        icon:`${process.env.PUBLIC_URL}/img/menuBarIcon/homeIcon.png`,
    },
    map:{
        displayName:"マップ",
        path:"/24th.kokasai.com/map",
        icon:`${process.env.PUBLIC_URL}/img/menuBarIcon/mapIcon.png`,
    },
    project:{
        displayName:"企画",
        path:"/24th.kokasai.com/project",
        icon:`${process.env.PUBLIC_URL}/img/menuBarIcon/projectIcon.png`,
    },
    credit:{
        displayName:"クレジット",
        path:"/24th.kokasai.com/credit",
    },
    apologize:{
        displayName:"作成中",
        path:"/24th.kokasai.com/apologize",
    },
    projectDetail:{
        displayName:"企画詳細",
        path:"/24th.kokasai.com/projectDetail",
    }
};
